# Makefile

RM = rm
binfile = ssmst_v1
objs = tree.o mstree.o

CXX = icpc
AR = xiar

#CFLAGS =  -O3 
CFLAGS = -fast -fPIC -xSSE4.1 

.SUFFIXES: .cpp .o


$(binfile): $(objs)
	$(CXX) -static -static-intel -o $(binfile) $(objs) libslidesort_v1.a

.cpp.o:
	$(CXX) $(CFLAGS) -c $<

.PHONY: clean
clean:
	$(RM) $(objs) *~ 

# ヘッダーファイルの依存関係
tree.o: olmst.h
mstree.o: olmst.h

